# Generated by Django 4.2.4 on 2023-08-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task_manager_app', '0002_alter_company_name_alter_customuser_company_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment',
            name='condition_at_assignment',
        ),
        migrations.DeleteModel(
            name='Log',
        ),
    ]
